server:
  port: 8088

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/notification_db?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_LqFNt8fcR6De
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # EMAIL AYARLARI (GMAIL ÖRNEĞİ)
  mail:
    host: smtp.gmail.com
    port: 587
    username: efecantekin@gmail.com # BURAYI DOLDUR
    password: efeKSK1912! # BURAYI DOLDUR (Google App Password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: rabbitmq # Docker Compose'daki servis adı
    port: 5672
    username: guest
    password: guest