version: "3.8"

services:
  # 1. VERİTABANI
  # postgres-db:
  #   image: postgres:15-alpine
  #   container_name: hr-postgres
  #   environment:
  #     - POSTGRES_USER=hr_admin
  #     - POSTGRES_PASSWORD=hr_password
  #     - POSTGRES_DB=hr_main_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #     - ./init-scripts:/docker-entrypoint-initdb.d
  #   networks:
  #     - hr-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U hr_admin -d hr_main_db"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # 2. AUTH SERVICE
  auth-service:
    build: ./auth-service
    container_name: hr-auth
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/auth_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De

    networks:
      - hr-network

  # 3. EMPLOYEE SERVICE
  employee-service:
    build: ./employee-service
    container_name: hr-employee
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/employee_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De
      - AUTH_URI=http://auth-service:8082

    networks:
      - hr-network

  # 4. LEAVE SERVICE
  leave-service:
    build: ./leave-service
    container_name: hr-leave
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/leave_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De

    networks:
      - hr-network

  # 5. DOCUMENT SERVICE
  document-service:
    build: ./document-service
    container_name: hr-document
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/doc_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De

    networks:
      - hr-network

    # 10. API GATEWAY
  api-gateway:
    build: ./api-gateway
    container_name: hr-gateway
    ports:
      - "8080:8080"
    environment:
      - EMPLOYEE_URI=http://employee-service:8081
      - AUTH_URI=http://auth-service:8082
      - LEAVE_URI=http://leave-service:8083
      - DOC_URI=http://document-service:8084
      - ADMIN_URI=http://admin-service:8085
      - RECRUITMENT_URI=http://recruitment-service:8086
      - PERFORMANCE_URI=http://performance-service:8087
      - NOTIFICATION_URI=http://notification-service:8088
    depends_on:
      - auth-service
      - employee-service
      - leave-service
      - document-service
      - admin-service
      - recruitment-service
      - performance-service
      - notification-service
    networks:
      - hr-network

  admin-service:
    build: ./admin-service
    container_name: hr-admin
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/admin_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De

    networks:
      - hr-network

  # 7. RECRUITMENT SERVICE
  recruitment-service:
    build: ./recruitment-service
    container_name: hr-recruitment
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/recruitment_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De

    networks:
      - hr-network

  # 8. PERFORMANCE SERVICE
  performance-service:
    build: ./performance-service
    container_name: hr-performance
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/performance_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De

    networks:
      - hr-network

  # 9. NOTIFICATION SERVICE
  notification-service:
    build: ./notification-service
    container_name: hr-notification
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-floral-wildflower-ag6dsgcp-pooler.c-2.eu-central-1.aws.neon.tech/notification_db?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner # Neon'dan aldığınız kullanıcı adı
      - SPRING_DATASOURCE_PASSWORD=npg_LqFNt8fcR6De
    networks:
      - hr-network

  # 11. FRONTEND
  hr-frontend:
    build: ./hr-frontend
    container_name: hr-frontend-app
    ports:
      - "3000:3000"
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge
