server:
  port: 8081

spring:
  application:
    name: employee-service
  
  datasource: 
    # Yerel Docker DB yerine dışarıdan (environment variable) gelen bulut DB adresini kullanıyoruz
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_db}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_LqFNt8fcR6De}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # --- HATA ÇÖZÜMÜ: RABBITMQ BAĞLANTI AYARLARI ---
  rabbitmq:
    host: rabbitmq # localhost yerine Docker servis adı kullanılmalı
    port: 5672
    username: guest
    password: guest

# Auth servis adresi
AUTH_SERVICE_URL: ${AUTH_URI:http://auth-service:8082}